### ISSUE TITLE
Program execution attribute missing error:  module 'snap7' has no attribute 'types'. Did you mean: 'type'

### ISSUE THREAD

**Issue by ycEducationAcc** [LiuYuancheng/PLC_and_RTU_Simulator#2]
Snap7-version: 2.0 

Error message: 

```
s7commServerInit > Host IP: 0.0.0.0, Port: 102
Start the S7comm event handling loop.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ncl/cidex2024/src/lib/rtuSimulator.py", line 207, in run
    self.server.startService(eventHandlerFun=self.ladderHandler)
  File "/home/ncl/cidex2024/src/lib/snap7Comm.py", line 311, in startService
    self.initRegisterArea()
  File "/home/ncl/cidex2024/src/lib/snap7Comm.py", line 273, in initRegisterArea
    self._server.register_area(snap7.types.srvAreaDB,
AttributeError: module 'snap7' has no attribute 'types'. Did you mean: 'type'?
```
I used Ubuntu 20.04 and I tried version 1.1 and 1.4 but got same error.

**Comment by LiuYuancheng** [comment]
Hi We did some test, and yes, we fond the same error. 

Currently the solution is: 

**For Windows_OS platform, install the version 1.1 or 1.3 :**
```
pip install setuptools
pip install python-snap7==1.1
```
or 
`pip install python-snap7==1.3`

**For Linux install, follow the  version 1.3 directly.** 
Ubuntu need to follow this link to install the lib first: https://python-snap7.readthedocs.io/en/latest/installation.html
```
$ sudo add-apt-repository ppa:gijzelaar/snap7
$ sudo apt-get update
$ sudo apt-get install libsnap7-1 libsnap7-dev
```
Then install version 1.3 with pip can solve the problem.
`pip install python-snap7==1.3`

**Comment by ycEducationAcc** [comment]
Thanks~ it works!

**Comment by LiuYuancheng** [comment]
Install the software-properties-common package using the [apt-get command](https://phoenixnap.com/kb/how-to-use-apt-get-commands):

sudo apt-get install software-properties-common
